#! /bin/sh
## STARTUP ##
sxhkd &
numlockx &
nitrogen --restore &
bash ~/.config/polybar/launch.sh &
picom &
xsetroot -cursor_name left_ptr & 

bspc monitor -d I II III IV V 


## WINDOW CONFIGUARTION ##


bspc config border_width        2 
bspc config window_gap          5 

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true



#### BSPWM COLORING ####


bspc config normal_border_color         "#1e1e1e"
bspc config active_border_color         "#f4f1ed"
bspc config focused_border_color        "#f4f1ed"
bspc config presel_feedback_color       "#f4f1ed"
bspc config urgent_border_color         "#f4f1ed"



## APPLICATION RULES ##
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Gpick state=floating
bspc rule -a Thunar state=floating
bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a TelegramDesktop state=floating follow=off desktop='^1'
bspc rule -a mpv state=floating rectangle=800x450+560+315 follow=off
bspc rule -a Media viewer rectangle=1350x900+285+90 state=floating
